services:
  memgraph:
    image: memgraph/memgraph:3.8.1
    container_name: codecortex-memgraph
    ports:
      - "7687:7687"
    volumes:
      - codecortex-memgraph:/var/lib/memgraph
    command:
      - "--also-log-to-stderr=true"
    environment:
      - MEMGRAPH_USER=memgraph
      - MEMGRAPH_PASSWORD=memgraph

volumes:
  codecortex-memgraph:
